default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: rails_tutorial
  pool: 5
  username: root
  password: aaa
  host: localhost
  # <<: *default
  # database: phase3_development

test:
  <<: *default
  database: phase3_test

production:
  <<: *default
  database: rails_tutorial
  username: root
  password: aaa
